name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  norminette:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: alexandregv/norminette-action@v3
        with:
          flags: 'src'

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Compile project
      run: make
      
    - name: Compile tests
      run: make maketest
      
    - name: Run tests
      run: make test
